notifications:
  email: false
language: python

matrix:
  include:
  - sudo: required
    services:
    - docker
    env: DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64
  - sudo: required
    services:
    - docker
    env: DOCKER_IMAGE=quay.io/pypa/manylinux1_i686 PRE_CMD=linux32

install:
  - docker pull $DOCKER_IMAGE

script:
  - docker run --rm -v `pwd`:/io $DOCKER_IMAGE $PRE_CMD /io/scripts/build_wheels.sh
  - cp wheelhouse/*manylinux*.whl $TRAVIS_BUILD_DIR

deploy:
  provider: releases
  api_key:
    secure: Rr3oLI2qsW918UEXmoYlygaP+9wY4S9HlBPO7Sv0NcMMciwsmcLi9bXTbclnMNmxJ4Ho+9fXScsekduW/3aNTiU5eLQLhqPzb/10lebjZ/m5k3HEXHLkKTFjIMYdqBov7JpZBd6KWqn+sKtNxwzAKTXiADLSAGv17DzTAK3iEoFa8sGshkNHKK/5TgOY5EilAIHIX7gooZE0mLJALsua8GyEXv8/UUJ3QU87eqIL9H3Ae4B5yy/DmeFHne5OHW6XqoC23MxES4qqzhPTYvnaWocbzAYMgFB64rhgs29hFTfERUdCMxfqKBYVBnXn7AO7t88Fra3ATj6nSZbg2fY+TzYvSXrCQZyk8LAgY0+hfpBEoOqv0jabpBROVw8s6W2vW0vYUjN5Rjn/+m5Og1ENOY+rQsut21EyhOOKqPlGlj7IE8d2GAqXsZVXj6zPOg4VXX88nPie+PHGpL81bYmrECXCWwgak63M8lpUAmLfwRQEGBPEwpafnst1N8mA83LTsP8+37RVQWjuCk28AiV7SQfBo6s9ERGfNAQEJqUy76aA8oOf2YZC6p7gbSTaJ336imm/dK18IKdWO/GDcWSGwbgYMgfsmAKTyLDsZ+xqV7t+byyR62l9Sw9161Z+bBq9AwhdU4Ka2bYaYdI0oZ6M4iaBMfu/B93Z7+bR2pZ080M=
  file_glob: true
  file: "*.whl"
  skip_cleanup: true
  on:
    repo: zehome/pysmbc-wheels
    tags: true
